# Generated by Django 2.1 on 2019-04-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Policy name.', max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(help_text='Policy description.', max_length=500, verbose_name='Description')),
                ('dependants', models.PositiveSmallIntegerField(default=1, help_text='Number of dependants covered.', verbose_name='Dependants')),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
            },
        ),
    ]
