# Generated by Django 2.1 on 2019-04-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='dependants',
            new_name='dependants_per_holder',
        ),
    ]
