# Generated by Django 2.1 on 2019-04-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_auto_20190424_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='cash_back_days',
            field=models.PositiveSmallIntegerField(default=6, help_text='Indicate the number of days without claiming qualifies a cash back.', verbose_name='Cash back days'),
        ),
    ]
