# Generated by Django 2.1 on 2019-04-24 12:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('relationship', models.CharField(choices=[('C', 'Child'), ('S', 'Spouse'), ('O', 'Other')], help_text='Relationship to policy registrant.', max_length=1, verbose_name='Relationship')),
                ('relationship_description', models.TextField(blank=True, help_text='If relationship is indicated as other, please explain relationship to dependant here.', null=True, verbose_name='Relationship description')),
                ('first_name', models.CharField(help_text="Family member's first name(s).", max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(help_text="Family member's last name.", max_length=255, verbose_name='Last name')),
                ('date_of_birth', models.DateField(help_text="Member's date of birth.", verbose_name='Date of birth')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], help_text="Member's sex orientation.", max_length=1, verbose_name='Sex')),
                ('date_joined', models.DateField(help_text='Date when member signed up for policy.', verbose_name='Date joined')),
            ],
            options={
                'verbose_name': 'Family member',
                'verbose_name_plural': 'Family members',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('first_name', models.CharField(help_text="Member's first name(s).", max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(help_text="Member's last name.", max_length=255, verbose_name='Last name')),
                ('national_id', models.CharField(help_text='National ID number.', max_length=12, verbose_name='National ID')),
                ('date_of_birth', models.DateField(help_text="Member's date of birth.", verbose_name='Date of birth')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], help_text="Member's sex orientation.", max_length=1, verbose_name='Sex')),
                ('date_joined', models.DateField(help_text='Date when member signed up for policy.', verbose_name='Date joined')),
                ('marital_status', models.CharField(choices=[('M', 'Married'), ('S', 'Single'), ('D', 'Divorced'), ('W', 'Widowed')], default='M', help_text="Member's marital status.", max_length=1, verbose_name='Marital status')),
                ('policy', models.ForeignKey(blank=True, help_text='Policy signed up for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='policies.Policy', verbose_name='Policy')),
            ],
            options={
                'verbose_name_plural': 'Members',
            },
        ),
        migrations.AddField(
            model_name='dependant',
            name='member',
            field=models.ForeignKey(help_text='Reference to policy registrant.', on_delete=django.db.models.deletion.CASCADE, related_name='dependants', to='members.Member', verbose_name='Member'),
        ),
    ]
