# Generated by Django 2.1 on 2019-04-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependant',
            options={'verbose_name': 'Dependant', 'verbose_name_plural': 'Family members'},
        ),
        migrations.AlterField(
            model_name='dependant',
            name='date_joined',
            field=models.DateField(help_text='Date when dependant was registered.', verbose_name='Date joined'),
        ),
        migrations.AlterField(
            model_name='dependant',
            name='date_of_birth',
            field=models.DateField(help_text="Dependant's date of birth.", verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='dependant',
            name='first_name',
            field=models.CharField(help_text="Dependant's first name(s).", max_length=255, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='dependant',
            name='last_name',
            field=models.CharField(help_text="Dependant's last name.", max_length=255, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='dependant',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], help_text="Dependant's sex orientation.", max_length=1, verbose_name='Sex'),
        ),
    ]
