# Generated by Django 2.1 on 2019-04-24 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20190424_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependant',
            options={'verbose_name': 'Dependant', 'verbose_name_plural': 'Dependants'},
        ),
    ]
