# Generated by Django 2.1 on 2019-04-24 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20190424_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='national_id',
            field=models.CharField(help_text='National ID number.', max_length=12, validators=[django.core.validators.RegexValidator(message='ID Number should match format like: 58 398766 B 25, without the spaces.', regex='\\d{2}\\d{6,7}[a-zA-Z]{1}\\d{2}')], verbose_name='National ID'),
        ),
    ]
