# Generated by Django 2.1 on 2019-04-24 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0005_auto_20190424_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='user_account',
            field=models.OneToOneField(blank=True, editable=False, help_text='User account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_record', to=settings.AUTH_USER_MODEL, verbose_name='User account'),
        ),
    ]
