# Generated by Django 2.1 on 2019-04-26 21:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_user_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date_of_claim', models.DateField(help_text='Date when claim was made.', verbose_name='Date of claim')),
                ('place_of_death', models.CharField(help_text='Place where policy dependant died.', max_length=255, verbose_name='Place of birth')),
                ('date_of_death', models.DateField(help_text='Date when the deceased died as reflected on death certificate.', verbose_name='Date of death')),
            ],
            options={
                'verbose_name_plural': 'Claims',
            },
        ),
        migrations.AddField(
            model_name='dependant',
            name='is_deceased',
            field=models.BooleanField(default=False, editable=False, help_text='Mark dependant as deceased.', verbose_name='Deceased'),
        ),
        migrations.AddField(
            model_name='claim',
            name='dependant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.Dependant', verbose_name='Dependant reference.'),
        ),
    ]
