# Generated by Django 2.1 on 2019-04-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='deceased_death_certificate',
            field=models.FileField(default='file.pdf', upload_to='requests/certs/', verbose_name="Deceased's death certificate"),
            preserve_default=False,
        ),
    ]
