# Generated by Django 2.1 on 2019-04-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_request_deceased_death_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email_address',
            field=models.EmailField(default='me@me.com', help_text='Member email address', max_length=254, verbose_name='Email addresss'),
            preserve_default=False,
        ),
    ]
