# Generated by Django 2.1 on 2019-04-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_member_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email_address',
            field=models.EmailField(help_text='Member email address', max_length=254, unique=True, verbose_name='Email address'),
        ),
    ]
