# Generated by Django 2.1 on 2019-04-28 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_auto_20190427_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.DecimalField(decimal_places=4, help_text='Amount Requested', max_digits=19, verbose_name='Amount')),
                ('paid_out', models.BooleanField(default=False, help_text='Paid out?', verbose_name='Paid out')),
            ],
            options={
                'verbose_name': 'Cash back request',
                'verbose_name_plural': 'Cash back requests',
            },
        ),
        migrations.AlterField(
            model_name='member',
            name='user_account',
            field=models.OneToOneField(blank=True, editable=False, help_text='User account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record', to=settings.AUTH_USER_MODEL, verbose_name='User account'),
        ),
        migrations.AddField(
            model_name='cashback',
            name='member',
            field=models.ForeignKey(help_text='Member reference.', on_delete=django.db.models.deletion.CASCADE, related_name='cashback_records', to='members.Member', verbose_name='Member'),
        ),
    ]
