# Generated by Django 2.1 on 2019-05-21 06:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_auto_20190429_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='members.Request')),
            ],
            options={
                'verbose_name': 'Request Payment',
                'verbose_name_plural': 'Request Payments',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('poll_url', models.URLField(blank=True, editable=False, null=True)),
                ('url', models.URLField(blank=True, editable=False, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reference')),
                ('value', models.DecimalField(decimal_places=2, editable=False, max_digits=19, verbose_name='Value')),
                ('paid', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=19, null=True, verbose_name='Amount paid')),
                ('completed', models.BooleanField(default=False, editable=False, verbose_name='Indicates if transaction was complete')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='requestpayment',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Transaction'),
        ),
    ]
